import { Metadata } from 'next'
import { Providers } from "@/redux/provider";

import { AppSidebar } from '@/components/app/AppSidebar/AppSidebar';
import ThemeBuilder from '@/styles/themeBuilder';

export const metadata: Metadata = {
  title: 'Supplementify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeBuilder>
            <AppSidebar />
            {children}
          </ThemeBuilder>
        </Providers>
      </body>
    </html>
  );
}